run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    go: "1.21"
  unused:
    go: "1.21"

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - gosimple
    - errcheck
    - revive
    - gosec

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0
