version: "2"

run:
  timeout: 5m
  tests: false
linters:
  default: all
  disable:
    # Explicitly disabled linters (as per requirements)
    - forbidigo # Forbid identifiers - too restrictive
    - exhaustruct # Exhaustive struct initialization - design choice
    - depguard # Import restrictions - not needed
    - lll # Line length - handled by gofmt
    - cyclop # Cyclomatic complexity - duplicate of gocyclo
    - funlen # Function length - overly strict
    - noinlineerr # Inline error handling | Community errror handling (makes no sense why we would want this)
    - varnamelen # Variable name length | I am 50/50 on this, there are times like it, but others like wg that are just go norms.
    - wsl # Deprecated - replaced by wsl_v5
  settings:
    wrapcheck:
      # Allow our custom error wrappers and common patterns
      ignore-sigs:
        - errors.New(
        - fmt.Errorf(
      ignore-package-globs:
        - "*.test"
        - "test/*"
        - "*_test.go"
    mnd:
      # Allow common patterns
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "10"
        - "60" # seconds/minutes
        - "100"
        - "1000"
        - "1024" # common buffer size
        - "4096" # common buffer size
      ignored-functions:
        - "make" # make([]int, 10)
        - "time.Sleep" # time.Sleep(5 * time.Second)
        - "time.Duration" # time.Duration(100)
        - "strconv.*" # strconv functions
      ignored-files:
        - "_test.go" # Tests often have test data numbers

# Formatters configuration (separate from linters)
formatters:
  disable:
    - gci # Import formatting - conflicts with goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
