# Docker Compose configuration for CloudMCP container testing
# This file provides a complete testing environment for container validation

version: '3.8'

services:
  # CloudMCP service under test
  cloudmcp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-dev}
    image: cloudmcp:test
    container_name: cloudmcp-test
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
      - ENABLE_METRICS=true
      - METRICS_PORT=8080
      - CLOUD_MCP_SERVER_NAME=CloudMCP-Test
    networks:
      - cloudmcp-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    mem_limit: 256m
    mem_reservation: 128m
    cpus: '0.5'

  # Test runner container for comprehensive testing
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: cloudmcp-test:runner
    container_name: cloudmcp-test-runner
    depends_on:
      cloudmcp:
        condition: service_healthy
    environment:
      - CLOUDMCP_URL=http://cloudmcp:8080
      - TEST_TIMEOUT=300
      - CONTAINER_TEST_MODE=true
    networks:
      - cloudmcp-test
    volumes:
      - ./test-results:/test-results
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["./scripts/docker-test.sh", "--skip-build"]

  # Security scanner service
  security-scanner:
    image: aquasec/trivy:latest
    container_name: cloudmcp-security-scanner
    depends_on:
      - cloudmcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./security-results:/results
    networks:
      - cloudmcp-test
    command: ["image", "--format", "json", "--output", "/results/security-scan.json", "cloudmcp:test"]

  # Performance testing service
  performance-tester:
    image: grafana/k6:latest
    container_name: cloudmcp-performance-tester
    depends_on:
      cloudmcp:
        condition: service_healthy
    volumes:
      - ./test/performance:/scripts
      - ./performance-results:/results
    networks:
      - cloudmcp-test
    environment:
      - CLOUDMCP_URL=http://cloudmcp:8080
    command: ["run", "--out", "json=/results/performance.json", "/scripts/load-test.js"]

networks:
  cloudmcp-test:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  test-results:
    driver: local
  security-results:
    driver: local
  performance-results:
    driver: local